### ISSUE TITLE
UWP ARM supported dll

### ISSUE THREAD

**Issue by AnandMulay** [keijiro/UnityRustStl#2]
This is a great example of loading  STL files runtime, but I want to know if it is possible to use this in UWP platform with ARM-supported dll, if so how can we do this?

**Comment by keijiro** [comment]
I think it's impossible because the Rust compiler doesn't support UWP.

You can find Rust for UWP using Google, but it's pretty experimental. You can give it a try by yourself if you have enough time for it (that's what I don't have).

**Comment by keijiro** [comment]
I'm closing this issue as "answered". Please reopen it for further problems.

**Comment by AnandMulay** [comment]
Thank you @keijiro, I'll give it a try, I hardly know about Rust though as I'm a unity developer.
can you just tell me how to create the dll files using that plugin, I believe its something using cmd/shell

**Comment by keijiro** [comment]
You can use `Plugin/build.sh`.

I explained how it works in [this video](https://www.youtube.com/watch?v=2e9HgBns92c). There is no English subtitles, though.

**Comment by AnandMulay** [comment]
Thanks again :)
